# MDPIC Configuration
## Docs: https://github.com/skycity233/MDPIC/README.md
## Source: https://github.com/skycity233/MDPIC

github_username: skycity233
repository_name: MYMDPIC
language: en-US
hotkey: f8

